backend:
  - changed-files:
      - any-glob-to-any-file: "backend/**"

frontend:
  - changed-files:
      - any-glob-to-any-file: "frontend/**"

infrastructure:
  - changed-files:
      - any-glob-to-any-file: "infra/**"

ci:
  - changed-files:
      - any-glob-to-any-file: ".github/**"

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.md"
          - "docs/**"

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - "backend/go.mod"
          - "backend/go.sum"
          - "frontend/package.json"
          - "frontend/package-lock.json"
