changelog:
  exclude:
    labels:
      - skip-changelog
  categories:
    - title: Breaking Changes
      labels:
        - breaking-change
    - title: New Features
      labels:
        - enhancement
    - title: Bug Fixes
      labels:
        - bug
    - title: Backend
      labels:
        - backend
    - title: Frontend
      labels:
        - frontend
    - title: Infrastructure
      labels:
        - infrastructure
    - title: CI / CD
      labels:
        - ci
    - title: Documentation
      labels:
        - documentation
    - title: Dependencies
      labels:
        - dependencies
    - title: Other Changes
      labels:
        - "*"
