package middleware

import (
	"fmt"
	"log/slog"
	"net/http"
	"strings"

	"github.com/gin-gonic/gin"
	"github.com/golang-jwt/jwt/v5"
)

// Claims represents the JWT claims issued by Auth.js (HS256, signed with AUTH_SECRET)
type Claims struct {
	Sub   string `json:"sub"`
	Email string `json:"email"`
	jwt.RegisteredClaims
}

// AuthMiddleware validates HS256 JWT tokens from the Authorization header.
// The token is generated by the frontend's Auth.js jwt callback and signed
// with the shared JWT_SECRET (== frontend AUTH_SECRET).
func AuthMiddleware(logger *slog.Logger, jwtSecret string) gin.HandlerFunc {
	return func(c *gin.Context) {
		authHeader := c.GetHeader("Authorization")
		if authHeader == "" {
			logger.Warn("missing authorization header")
			c.JSON(http.StatusUnauthorized, gin.H{"error": "missing authorization header"})
			c.Abort()
			return
		}

		parts := strings.Split(authHeader, " ")
		if len(parts) != 2 || parts[0] != "Bearer" {
			logger.Warn("invalid authorization header format")
			c.JSON(http.StatusUnauthorized, gin.H{"error": "invalid authorization header"})
			c.Abort()
			return
		}

		tokenString := parts[1]

		claims, err := ValidateJWTToken(tokenString, jwtSecret)
		if err != nil {
			logger.Warn("invalid or expired token", "error", err)
			c.JSON(http.StatusUnauthorized, gin.H{"error": "invalid or expired token"})
			c.Abort()
			return
		}

		if claims.Sub == "" {
			logger.Warn("missing subject claim in token")
			c.JSON(http.StatusUnauthorized, gin.H{"error": "invalid token claims"})
			c.Abort()
			return
		}

		c.Set("user_id", claims.Sub)
		c.Set("user_email", claims.Email)
		c.Set("claims", claims)

		c.Next()
	}
}

// ValidateJWTToken parses and validates an Auth.js HS256 token.
func ValidateJWTToken(tokenString, jwtSecret string) (*Claims, error) {
	claims := &Claims{}
	token, err := jwt.ParseWithClaims(tokenString, claims, func(token *jwt.Token) (interface{}, error) {
		if _, ok := token.Method.(*jwt.SigningMethodHMAC); !ok {
			return nil, jwt.ErrSignatureInvalid
		}
		return []byte(jwtSecret), nil
	})
	if err != nil {
		return nil, err
	}
	if !token.Valid {
		return nil, fmt.Errorf("token is invalid")
	}
	if claims.Sub == "" {
		return nil, fmt.Errorf("missing subject claim")
	}
	return claims, nil
}

// GetUserID retrieves the user ID from the request context
func GetUserID(c *gin.Context) string {
	userID, _ := c.Get("user_id")
	if id, ok := userID.(string); ok {
		return id
	}
	return ""
}

// GetUserEmail retrieves the user email from the request context
func GetUserEmail(c *gin.Context) string {
	email, _ := c.Get("user_email")
	if e, ok := email.(string); ok {
		return e
	}
	return ""
}
