services:
  devcontainer:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    hostname: project-ostgut-dev
    image: project-ostgut-dev:latest
    volumes:
      - ..:/workspace:cached
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "3000:3000"  # Frontend
      - "8080:8080"  # Backend API
    depends_on:
      postgres:
        condition: service_healthy
    command: sleep infinity
