import type { Station } from '@/types/player'
import type { ApiStation } from '@/types/station'

export function toStation(s: ApiStation): Station {
    return {
        id: s.id,
        name: s.name,
        streamUrl: s.stream_url,
        streams: s.streams?.map((st) => ({
            id: st.id,
            url: st.url,
            resolvedUrl: st.resolved_url,
            kind: st.kind,
            container: st.container,
            transport: st.transport,
            mimeType: st.mime_type,
            codec: st.codec,
            lossless: st.lossless,
            bitrate: st.bitrate,
            bitDepth: st.bit_depth,
            sampleRateHz: st.sample_rate_hz,
            sampleRateConfidence: st.sample_rate_confidence,
            channels: st.channels,
            priority: st.priority,
            isActive: st.is_active,
            metadataEnabled: st.metadata_enabled,
            metadataType: st.metadata_type,
            metadataSource: st.metadata_source,
            metadataUrl: st.metadata_url,
            metadataResolver: st.metadata_resolver,
            metadataResolverCheckedAt: st.metadata_resolver_checked_at,
            healthScore: st.health_score,
            loudnessIntegratedLufs: st.loudness_integrated_lufs,
            loudnessPeakDbfs: st.loudness_peak_dbfs,
            loudnessSampleDurationSeconds: st.loudness_sample_duration_seconds,
            loudnessMeasuredAt: st.loudness_measured_at,
            loudnessMeasurementStatus: st.loudness_measurement_status,
            lastCheckedAt: st.last_checked_at,
            lastError: st.last_error,
        })),
        logo: s.logo,
        genres: s.genre_tags ?? [],
        country: s.country,
        city: s.city,
        bitrate: s.bitrate,
        codec: s.codec,
    }
}
